package gui;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.EmptyBorder;

/**
 * MainWindow. Clase que se encarga de la gestion de la ventana principal de la
 * interfaz gráfica.
 * 
 * @author Javier Martinez
 * @author Daniel Puente
 * @author Jaime Sagüillo
 * @author Jorge Zamora
 * @author Oscar Fernandez
 *
 */
public class MainWindow extends JFrame {

	/**
	 * Auto generated by eclipse
	 */
	private static final long serialVersionUID = -7203217001393533800L;
	/**
	 * contentPane
	 */
	private JPanel contentPane;
	/**
	 * typeCombo
	 */
	private JComboBox typeCombo;
	/**
	 * types
	 */
	private static final String[] types = new String[] { "Contactos", "Llamadas", "Tipos de contacto" };
	/**
	 * persistenceTypes
	 */
	private static final String[] persistenceTypes = new String[] { "Base de datos", "Ficheros binario" };
	/**
	 * selectTab
	 */
	private SelectTab selectTab;
	/**
	 * updateTab
	 */
	private UpdateTab updateTab;
	/**
	 * insertTab
	 */
	private InsertTab insertTab;
	/**
	 * persistCombo
	 */
	private JComboBox persistCombo;

	/**
	 * Create the frame.
	 */
	public MainWindow() {
		setTitle("Persistent Agenda");
		initializeMainWindow();

		JTabbedPane tabbedPane = new JTabbedPane(JTabbedPane.TOP);
		GroupLayout gl_contentPane = new GroupLayout(contentPane);

		initializeComboButsBar(tabbedPane, gl_contentPane);

		initializeTabBar(tabbedPane, gl_contentPane);

		initializeActionListeners();
	}

	/**
	 * Método initializeActionListeners. Método que se encarga de la
	 * inicialización de los listeners.
	 */
	private void initializeActionListeners() {
		typeComboListener();
	}

	/**
	 * Método typeComboListener. Método que se encarga de
	 */
	private void typeComboListener() {
		typeCombo.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (typeCombo.getSelectedItem().toString() == types[0]) {
					selectTab.setView(0);
					updateTab.setView(0);
					insertTab.setView(0);
				} else if (typeCombo.getSelectedItem().toString() == types[1]) {
					selectTab.setView(1);
					updateTab.setView(1);
					insertTab.setView(1);
				} else {
					selectTab.setView(2);
					updateTab.setView(2);
					insertTab.setView(2);
				}
				contentPane.repaint();
			}
		});
	}

	// TODO Cuidado no es utiliza este método
	/**
	 * Método persistenceComboListener. Método que se encarga de cambiar la
	 * persistencia dentro del comboListener.
	 */
	private void persistenceComboListener() {
		persistCombo.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				MainGUI.changePersistence(persistCombo.getSelectedIndex());
			}
		});
	}

	/**
	 * Método initializeTabBar. Método que se encarga de inizializar barra de
	 * pestañas.
	 * 
	 * @param tabbedPane
	 *            Panel sobre el que trabajar
	 * @param gl_contentPane
	 */
	private void initializeTabBar(JTabbedPane tabbedPane, GroupLayout gl_contentPane) {

		contentPane.setLayout(gl_contentPane);

		insertTab = new InsertTab(tabbedPane);

		updateTab = new UpdateTab(tabbedPane); // :D

		selectTab = new SelectTab(tabbedPane);
	}

	/**
	 * Método initializeComboButsBar. Método que se encarga de
	 * 
	 * @param tabbedPane
	 * @param gl_contentPane
	 */
	private void initializeComboButsBar(JTabbedPane tabbedPane, GroupLayout gl_contentPane) {
		JPanel panel = new JPanel();
		// Group layout generado automaticamente
		gl_contentPane
				.setHorizontalGroup(
						gl_contentPane.createParallelGroup(Alignment.LEADING)
								.addGroup(gl_contentPane.createSequentialGroup()
										.addComponent(panel, GroupLayout.PREFERRED_SIZE, 262,
												GroupLayout.PREFERRED_SIZE)
										.addContainerGap(162, Short.MAX_VALUE))
								.addComponent(tabbedPane, GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE));
		gl_contentPane.setVerticalGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPane.createSequentialGroup()
						.addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(tabbedPane, GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)));

		persistCombo = new JComboBox();
		panel.add(persistCombo);
		persistCombo.setModel(new DefaultComboBoxModel(persistenceTypes));

		typeCombo = new JComboBox();

		typeCombo.setModel(new DefaultComboBoxModel(types));
		panel.add(typeCombo);
	}

	/**
	 * Método initializeMainWindow. Método que se encarga de inicializar la
	 * ventana principal de la interfaz gráfica.
	 */
	private void initializeMainWindow() {
		// Inicialización de la ventana principal
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 500, 400);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));

		JScrollPane scroll = new JScrollPane(contentPane);

		setContentPane(scroll);
	}
}
